name: Terraform Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      action:
        required: true
        type: string
        default: plan
      aws_region:
        required: false
        type: string
        default: us-east-2
      tf_dir:
        description: "Ruta al directorio con .tf dentro del repo de infra"
        required: false
        type: string
        default: ./environments/${{ inputs.environment }}
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ inputs.aws_region }}
    steps:
      - name: Checkout infra repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws_region }}

      - name: Lista
        run: ls -l

      - name: Terraform Init
        run: terraform -chdir="${{ inputs.tf_dir }}"  init

      - name: Terraform Plan/Apply/Destroy
        run: |
          case "${{ inputs.action }}" in
            plan) terraform -chdir="${{ inputs.tf_dir }}" plan -var="environment=${{ inputs.environment }}" ;;
            apply) terraform -chdir="${{ inputs.tf_dir }}" apply -auto-approve -var="environment=${{ inputs.environment }}" ;;
            destroy) terraform -chdir="${{ inputs.tf_dir }}" destroy -auto-approve -var="environment=${{ inputs.environment }}" ;;
          esac
