on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      action:
        required: true
        type: string
      aws_region:
        required: false
        type: string
        default: us-east-2
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ inputs.aws_region }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Configure AWS credentials (opcional si usás creds estáticas)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Terraform Init
        run: terraform init
      - name: Terraform Plan/Apply/Destroy
        run: |
          case "${{ inputs.action }}" in
            plan) terraform plan -var="environment=${{ inputs.environment }}" ;;
            apply) terraform apply -auto-approve -var="environment=${{ inputs.environment }}" ;;
            destroy) terraform destroy -auto-approve -var="environment=${{ inputs.environment }}" ;;
          esac
