name: Terraform Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      action:
        required: true
        type: string
        default: plan
      aws_region:
        required: false
        type: string
        default: us-east-2
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      INFRA_REPO_TOKEN:
        required: true

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ inputs.aws_region }}
      TF_DIR: environments/${{ inputs.environment }}
    steps:
      - name: Checkout infra repo
        uses: actions/checkout@v4
        with:
          repository: Letterbox-discovery-recommendations/terraform
          ref: main
          token: ${{ secrets.INFRA_REPO_TOKEN }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws_region }}

      - name: List
        run: ls -l
      
      - name: Terraform Init
        run: terraform -chdir="${{ env.TF_DIR }}" init

      - name: Terraform Plan/Apply/Destroy
        run: |
          case "${{ inputs.action }}" in
            plan) terraform -chdir="${{ env.TF_DIR }}" plan -var="environment=${{ inputs.environment }}" ;;
            apply) terraform -chdir="${{ env.TF_DIR }}" apply -auto-approve -var="environment=${{ inputs.environment }}" ;;
            destroy) terraform -chdir="${{ env.TF_DIR }}" destroy -auto-approve -var="environment=${{ inputs.environment }}" ;;
          esac
